<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Interfaces\Persistence\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\persistence.silisync\persistence.silisync.csproj" />
      <ProjectReference Include="..\domain.silisync\domain.silisync.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.3.12" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.19" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.18" />
      <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.18" />
    </ItemGroup>

</Project>
